### ISSUE TITLE
Safe to delete repo

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio_rnaseq_output_example#3]
@chapmanb @roryk @lpantano This repo is safe to delete. I added additional coverage for R Markdown templates in the latest bcbioRNASeq release here: https://github.com/hbc/bcbioRNASeq/tree/master/tests/testthat-extra

Hope you all are doing well.

Best,
Mike

**Comment by roryk** [comment]
Thanks Mike! Hope you are doing well as well! I'm keeping this for now since bcbio is running the old version of bcbioRNASeq since we haven't moved to R 3.6 yet.
